### PR TITLE
Use os.path.normpath to stay platform agnostic

### PR DESCRIPTION
**Pull request by nalyDylan**
A commit to switch to os.path.normpath to fix issues with Linux

### CODE REVIEW

**Comment by nalyDylan** [comment]
Someone should probably confirm this works on Windows, but the documentation says the function converts / to \ on Windows also

**Comment by nalyDylan** [comment]
Nvm I ran it in a VM and it produces bad builds, any thoughts @MelonSpeedruns ?

**Comment by nalyDylan** [comment]
I solved the issue with the above commit, the aoc folder was no longer being named to Aoc, I cleaned that up and some other places where it didn't matter on Windows that the folder wasn't case-sensitive.

The script now makes graphicsPacks that run on my Linux Cemu when generated on either Windows or Linux

**Comment by MelonSpeedruns** [comment]
While I super appreciate the pull request, the Randomizer is now C# based, meaning that the code you wrote won't work anymore. Thank you so much for your interest!

**Pull request closed without merging**
